apiVersion: v1
kind: Service
metadata:
  name: kuro
  namespace: kuro
spec:
  selector:
    app: kuro
  ports:
    - name: http
      port: 80
      targetPort: 43211
      protocol: TCP
  type: ClusterIP
